version: '3.7'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - my-app
      - my-client
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - network1

  my-app:
    container_name: my-app
    build:
      context: ./web-service
      dockerfile: Dockerfile
    image: my-app
    networks:
      - network1

  my-client:
    container_name: my-client
    image: "node:10.15.3-alpine"
    working_dir: /home/node/app
    volumes:
      - ./web-client:/home/node/app
    expose:
      - "3000"
    command: "npm start"

networks:
  network1:
