version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - network1

  my-app:
    container_name: my-app
    build:
      context: ./web-service
      dockerfile: Dockerfile
    image: my-app
    networks:
      - network1

  my-client:
    container_name: my-client
    build:
      context: ./web-client
      dockerfile: Dockerfile.dev
    image: my-client
    networks:
      - network1

networks:
  network1:
